import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import  { Navbar } from "./components/Navbar";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { isAuthenticated } from "./components/Navbar"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AuthGlide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            < Navbar isAuthenticated={isAuthenticated} />
            { children }

          </ThemeProvider>
          
          </body>
    </html>
  );
}
